#!/bin/sh
# https://api.papermc.io/v2/projects/paper/versions/1.21.1/builds/57/downloads/paper-1.21.1-57.jar
argument=$1
VERSION=$(curl -s https://api.papermc.io/v2/projects/paper | \
    jq -r '.versions[-1]')
BUILD=$(curl -s https://api.papermc.io/v2/projects/paper/versions/${VERSION}/builds | \
    jq '.builds | map(select(.channel == "default") | .build) | .[-1]')
FILE_URL=https://api.papermc.io/v2/projects/paper/versions/${VERSION}/builds/${BUILD}/downloads/paper-${VERSION}-${BUILD}.jar
DIR=".server"

if [ ${argument} == "start" ]; then
  if [ ! -d $DIR ]; then
      mkdir $DIR
  fi

elif [ ${argument} == "version" ]; then
    echo "version"
else
  echo "사용법"
fi